name: EliteMine
version: $version$
main: com.koletar.jj.mineresetlite.MineResetLite
author: jjkoletar
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core]
commands:
  mineresetlite:
    aliases: [em, mines, mine, minereset]
    description: Manage mines.
